drop extension if exists "pg_net";

create sequence "public"."article_id_seq";

create sequence "public"."categorie_id_seq";

create sequence "public"."mode_respiratoire_id_seq";

create sequence "public"."role_id_seq";

create sequence "public"."seance_id_seq";

create sequence "public"."utilisateur_id_seq";


  create table "public"."categorie" (
    "id" integer not null default nextval('public.categorie_id_seq'::regclass),
    "nom" text not null
      );



  create table "public"."info_articles" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "title" text not null,
    "content" text not null,
    "tag" text,
    "tagArray" text[],
    "categories" text[] default '{}'::text[]
      );


alter table "public"."info_articles" enable row level security;


  create table "public"."info_resources" (
    "id" uuid not null default gen_random_uuid(),
    "title" text not null,
    "items" text[] not null
      );


alter table "public"."info_resources" enable row level security;


  create table "public"."mode_respiratoire" (
    "id" integer not null default nextval('public.mode_respiratoire_id_seq'::regclass),
    "libelle" text not null,
    "description" text,
    "temps_inspiration" integer not null,
    "temps_apnee" integer default 0,
    "temps_expiration" integer not null
      );


alter table "public"."mode_respiratoire" enable row level security;


  create table "public"."moderation" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "libelle" text
      );


alter table "public"."moderation" enable row level security;


  create table "public"."profiles" (
    "id" uuid not null,
    "email" text,
    "username" text
      );



  create table "public"."ressource" (
    "id" integer not null default nextval('public.article_id_seq'::regclass),
    "titre" text not null,
    "contenu" text not null,
    "date_publication" timestamp with time zone default now(),
    "statut" text default 'brouillon'::text,
    "categorie_id" integer,
    "auteur_id" integer
      );



  create table "public"."role" (
    "id" integer not null default nextval('public.role_id_seq'::regclass),
    "nom" text not null
      );



  create table "public"."seance" (
    "id" integer not null default nextval('public.seance_id_seq'::regclass),
    "date_debut" timestamp with time zone default now(),
    "duree_totale" integer not null,
    "utilisateur_id" integer,
    "mode_respiratoire_id" integer
      );



  create table "public"."utilisateur" (
    "id" integer not null default nextval('public.utilisateur_id_seq'::regclass),
    "nom" text,
    "prenom" text,
    "email" text not null,
    "mdp_hash" text not null,
    "date_inscription" timestamp with time zone default now(),
    "est_actif" boolean default true,
    "role_id" integer default 1,
    "username" text
      );


alter sequence "public"."article_id_seq" owned by "public"."ressource"."id";

alter sequence "public"."categorie_id_seq" owned by "public"."categorie"."id";

alter sequence "public"."mode_respiratoire_id_seq" owned by "public"."mode_respiratoire"."id";

alter sequence "public"."role_id_seq" owned by "public"."role"."id";

alter sequence "public"."seance_id_seq" owned by "public"."seance"."id";

alter sequence "public"."utilisateur_id_seq" owned by "public"."utilisateur"."id";

CREATE UNIQUE INDEX article_pkey ON public.ressource USING btree (id);

CREATE UNIQUE INDEX categorie_nom_key ON public.categorie USING btree (nom);

CREATE UNIQUE INDEX categorie_pkey ON public.categorie USING btree (id);

CREATE UNIQUE INDEX info_articles_pkey ON public.info_articles USING btree (id);

CREATE UNIQUE INDEX info_resources_pkey ON public.info_resources USING btree (id);

CREATE UNIQUE INDEX mode_respiratoire_pkey ON public.mode_respiratoire USING btree (id);

CREATE UNIQUE INDEX moderation_pkey ON public.moderation USING btree (id);

CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);

CREATE UNIQUE INDEX role_nom_key ON public.role USING btree (nom);

CREATE UNIQUE INDEX role_pkey ON public.role USING btree (id);

CREATE UNIQUE INDEX seance_pkey ON public.seance USING btree (id);

CREATE UNIQUE INDEX utilisateur_email_key ON public.utilisateur USING btree (email);

CREATE UNIQUE INDEX utilisateur_pkey ON public.utilisateur USING btree (id);

alter table "public"."categorie" add constraint "categorie_pkey" PRIMARY KEY using index "categorie_pkey";

alter table "public"."info_articles" add constraint "info_articles_pkey" PRIMARY KEY using index "info_articles_pkey";

alter table "public"."info_resources" add constraint "info_resources_pkey" PRIMARY KEY using index "info_resources_pkey";

alter table "public"."mode_respiratoire" add constraint "mode_respiratoire_pkey" PRIMARY KEY using index "mode_respiratoire_pkey";

alter table "public"."moderation" add constraint "moderation_pkey" PRIMARY KEY using index "moderation_pkey";

alter table "public"."profiles" add constraint "profiles_pkey" PRIMARY KEY using index "profiles_pkey";

alter table "public"."ressource" add constraint "article_pkey" PRIMARY KEY using index "article_pkey";

alter table "public"."role" add constraint "role_pkey" PRIMARY KEY using index "role_pkey";

alter table "public"."seance" add constraint "seance_pkey" PRIMARY KEY using index "seance_pkey";

alter table "public"."utilisateur" add constraint "utilisateur_pkey" PRIMARY KEY using index "utilisateur_pkey";

alter table "public"."categorie" add constraint "categorie_nom_key" UNIQUE using index "categorie_nom_key";

alter table "public"."profiles" add constraint "profiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profiles" validate constraint "profiles_id_fkey";

alter table "public"."ressource" add constraint "article_auteur_id_fkey" FOREIGN KEY (auteur_id) REFERENCES public.utilisateur(id) not valid;

alter table "public"."ressource" validate constraint "article_auteur_id_fkey";

alter table "public"."ressource" add constraint "article_categorie_id_fkey" FOREIGN KEY (categorie_id) REFERENCES public.categorie(id) not valid;

alter table "public"."ressource" validate constraint "article_categorie_id_fkey";

alter table "public"."ressource" add constraint "ressource_id_fkey" FOREIGN KEY (id) REFERENCES public.moderation(id) not valid;

alter table "public"."ressource" validate constraint "ressource_id_fkey";

alter table "public"."role" add constraint "role_nom_key" UNIQUE using index "role_nom_key";

alter table "public"."seance" add constraint "seance_mode_respiratoire_id_fkey" FOREIGN KEY (mode_respiratoire_id) REFERENCES public.mode_respiratoire(id) not valid;

alter table "public"."seance" validate constraint "seance_mode_respiratoire_id_fkey";

alter table "public"."seance" add constraint "seance_utilisateur_id_fkey" FOREIGN KEY (utilisateur_id) REFERENCES public.utilisateur(id) ON DELETE CASCADE not valid;

alter table "public"."seance" validate constraint "seance_utilisateur_id_fkey";

alter table "public"."utilisateur" add constraint "utilisateur_email_key" UNIQUE using index "utilisateur_email_key";

alter table "public"."utilisateur" add constraint "utilisateur_role_id_fkey" FOREIGN KEY (role_id) REFERENCES public.role(id) not valid;

alter table "public"."utilisateur" validate constraint "utilisateur_role_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.utilisateur (
    nom, 
    prenom, 
    email, 
    mdp_hash, 
    role_id, 
    est_actif,
    username
  )
  values (
    -- On laisse Nom et Prénom vides (NULL) par défaut
    null, 
    null, 
    
    new.email, 
    'SUPABASE_AUTH_MANAGED', 
    1, 
    true,
    
    -- On récupère le username de GitHub/Discord
    -- S'il n'existe pas (inscription email), on peut soit mettre NULL, 
    -- soit garder l'astuce du début de l'email. Ici, je mets NULL si pas trouvé :
    coalesce(
      new.raw_user_meta_data->>'user_name',          -- Spécifique GitHub
      new.raw_user_meta_data->>'preferred_username',  -- GitHub / Discord (parfois)
      new.raw_user_meta_data->>'full_name',           -- Discord / Google
      new.raw_user_meta_data->>'name',                -- Discord / Google (fallback)
      split_part(new.email, '@', 1)                  -- Si vraiment rien n'est trouvé (Email classique)
    )
  );
  return new;
end;
$function$
;

grant delete on table "public"."categorie" to "anon";

grant insert on table "public"."categorie" to "anon";

grant references on table "public"."categorie" to "anon";

grant select on table "public"."categorie" to "anon";

grant trigger on table "public"."categorie" to "anon";

grant truncate on table "public"."categorie" to "anon";

grant update on table "public"."categorie" to "anon";

grant delete on table "public"."categorie" to "authenticated";

grant insert on table "public"."categorie" to "authenticated";

grant references on table "public"."categorie" to "authenticated";

grant select on table "public"."categorie" to "authenticated";

grant trigger on table "public"."categorie" to "authenticated";

grant truncate on table "public"."categorie" to "authenticated";

grant update on table "public"."categorie" to "authenticated";

grant delete on table "public"."categorie" to "service_role";

grant insert on table "public"."categorie" to "service_role";

grant references on table "public"."categorie" to "service_role";

grant select on table "public"."categorie" to "service_role";

grant trigger on table "public"."categorie" to "service_role";

grant truncate on table "public"."categorie" to "service_role";

grant update on table "public"."categorie" to "service_role";

grant delete on table "public"."info_articles" to "anon";

grant insert on table "public"."info_articles" to "anon";

grant references on table "public"."info_articles" to "anon";

grant select on table "public"."info_articles" to "anon";

grant trigger on table "public"."info_articles" to "anon";

grant truncate on table "public"."info_articles" to "anon";

grant update on table "public"."info_articles" to "anon";

grant delete on table "public"."info_articles" to "authenticated";

grant insert on table "public"."info_articles" to "authenticated";

grant references on table "public"."info_articles" to "authenticated";

grant select on table "public"."info_articles" to "authenticated";

grant trigger on table "public"."info_articles" to "authenticated";

grant truncate on table "public"."info_articles" to "authenticated";

grant update on table "public"."info_articles" to "authenticated";

grant delete on table "public"."info_articles" to "service_role";

grant insert on table "public"."info_articles" to "service_role";

grant references on table "public"."info_articles" to "service_role";

grant select on table "public"."info_articles" to "service_role";

grant trigger on table "public"."info_articles" to "service_role";

grant truncate on table "public"."info_articles" to "service_role";

grant update on table "public"."info_articles" to "service_role";

grant delete on table "public"."info_resources" to "anon";

grant insert on table "public"."info_resources" to "anon";

grant references on table "public"."info_resources" to "anon";

grant select on table "public"."info_resources" to "anon";

grant trigger on table "public"."info_resources" to "anon";

grant truncate on table "public"."info_resources" to "anon";

grant update on table "public"."info_resources" to "anon";

grant delete on table "public"."info_resources" to "authenticated";

grant insert on table "public"."info_resources" to "authenticated";

grant references on table "public"."info_resources" to "authenticated";

grant select on table "public"."info_resources" to "authenticated";

grant trigger on table "public"."info_resources" to "authenticated";

grant truncate on table "public"."info_resources" to "authenticated";

grant update on table "public"."info_resources" to "authenticated";

grant delete on table "public"."info_resources" to "service_role";

grant insert on table "public"."info_resources" to "service_role";

grant references on table "public"."info_resources" to "service_role";

grant select on table "public"."info_resources" to "service_role";

grant trigger on table "public"."info_resources" to "service_role";

grant truncate on table "public"."info_resources" to "service_role";

grant update on table "public"."info_resources" to "service_role";

grant delete on table "public"."mode_respiratoire" to "anon";

grant insert on table "public"."mode_respiratoire" to "anon";

grant references on table "public"."mode_respiratoire" to "anon";

grant select on table "public"."mode_respiratoire" to "anon";

grant trigger on table "public"."mode_respiratoire" to "anon";

grant truncate on table "public"."mode_respiratoire" to "anon";

grant update on table "public"."mode_respiratoire" to "anon";

grant delete on table "public"."mode_respiratoire" to "authenticated";

grant insert on table "public"."mode_respiratoire" to "authenticated";

grant references on table "public"."mode_respiratoire" to "authenticated";

grant select on table "public"."mode_respiratoire" to "authenticated";

grant trigger on table "public"."mode_respiratoire" to "authenticated";

grant truncate on table "public"."mode_respiratoire" to "authenticated";

grant update on table "public"."mode_respiratoire" to "authenticated";

grant delete on table "public"."mode_respiratoire" to "service_role";

grant insert on table "public"."mode_respiratoire" to "service_role";

grant references on table "public"."mode_respiratoire" to "service_role";

grant select on table "public"."mode_respiratoire" to "service_role";

grant trigger on table "public"."mode_respiratoire" to "service_role";

grant truncate on table "public"."mode_respiratoire" to "service_role";

grant update on table "public"."mode_respiratoire" to "service_role";

grant delete on table "public"."moderation" to "anon";

grant insert on table "public"."moderation" to "anon";

grant references on table "public"."moderation" to "anon";

grant select on table "public"."moderation" to "anon";

grant trigger on table "public"."moderation" to "anon";

grant truncate on table "public"."moderation" to "anon";

grant update on table "public"."moderation" to "anon";

grant delete on table "public"."moderation" to "authenticated";

grant insert on table "public"."moderation" to "authenticated";

grant references on table "public"."moderation" to "authenticated";

grant select on table "public"."moderation" to "authenticated";

grant trigger on table "public"."moderation" to "authenticated";

grant truncate on table "public"."moderation" to "authenticated";

grant update on table "public"."moderation" to "authenticated";

grant delete on table "public"."moderation" to "service_role";

grant insert on table "public"."moderation" to "service_role";

grant references on table "public"."moderation" to "service_role";

grant select on table "public"."moderation" to "service_role";

grant trigger on table "public"."moderation" to "service_role";

grant truncate on table "public"."moderation" to "service_role";

grant update on table "public"."moderation" to "service_role";

grant delete on table "public"."profiles" to "anon";

grant insert on table "public"."profiles" to "anon";

grant references on table "public"."profiles" to "anon";

grant select on table "public"."profiles" to "anon";

grant trigger on table "public"."profiles" to "anon";

grant truncate on table "public"."profiles" to "anon";

grant update on table "public"."profiles" to "anon";

grant delete on table "public"."profiles" to "authenticated";

grant insert on table "public"."profiles" to "authenticated";

grant references on table "public"."profiles" to "authenticated";

grant select on table "public"."profiles" to "authenticated";

grant trigger on table "public"."profiles" to "authenticated";

grant truncate on table "public"."profiles" to "authenticated";

grant update on table "public"."profiles" to "authenticated";

grant delete on table "public"."profiles" to "service_role";

grant insert on table "public"."profiles" to "service_role";

grant references on table "public"."profiles" to "service_role";

grant select on table "public"."profiles" to "service_role";

grant trigger on table "public"."profiles" to "service_role";

grant truncate on table "public"."profiles" to "service_role";

grant update on table "public"."profiles" to "service_role";

grant delete on table "public"."ressource" to "anon";

grant insert on table "public"."ressource" to "anon";

grant references on table "public"."ressource" to "anon";

grant select on table "public"."ressource" to "anon";

grant trigger on table "public"."ressource" to "anon";

grant truncate on table "public"."ressource" to "anon";

grant update on table "public"."ressource" to "anon";

grant delete on table "public"."ressource" to "authenticated";

grant insert on table "public"."ressource" to "authenticated";

grant references on table "public"."ressource" to "authenticated";

grant select on table "public"."ressource" to "authenticated";

grant trigger on table "public"."ressource" to "authenticated";

grant truncate on table "public"."ressource" to "authenticated";

grant update on table "public"."ressource" to "authenticated";

grant delete on table "public"."ressource" to "service_role";

grant insert on table "public"."ressource" to "service_role";

grant references on table "public"."ressource" to "service_role";

grant select on table "public"."ressource" to "service_role";

grant trigger on table "public"."ressource" to "service_role";

grant truncate on table "public"."ressource" to "service_role";

grant update on table "public"."ressource" to "service_role";

grant delete on table "public"."role" to "anon";

grant insert on table "public"."role" to "anon";

grant references on table "public"."role" to "anon";

grant select on table "public"."role" to "anon";

grant trigger on table "public"."role" to "anon";

grant truncate on table "public"."role" to "anon";

grant update on table "public"."role" to "anon";

grant delete on table "public"."role" to "authenticated";

grant insert on table "public"."role" to "authenticated";

grant references on table "public"."role" to "authenticated";

grant select on table "public"."role" to "authenticated";

grant trigger on table "public"."role" to "authenticated";

grant truncate on table "public"."role" to "authenticated";

grant update on table "public"."role" to "authenticated";

grant delete on table "public"."role" to "service_role";

grant insert on table "public"."role" to "service_role";

grant references on table "public"."role" to "service_role";

grant select on table "public"."role" to "service_role";

grant trigger on table "public"."role" to "service_role";

grant truncate on table "public"."role" to "service_role";

grant update on table "public"."role" to "service_role";

grant delete on table "public"."seance" to "anon";

grant insert on table "public"."seance" to "anon";

grant references on table "public"."seance" to "anon";

grant select on table "public"."seance" to "anon";

grant trigger on table "public"."seance" to "anon";

grant truncate on table "public"."seance" to "anon";

grant update on table "public"."seance" to "anon";

grant delete on table "public"."seance" to "authenticated";

grant insert on table "public"."seance" to "authenticated";

grant references on table "public"."seance" to "authenticated";

grant select on table "public"."seance" to "authenticated";

grant trigger on table "public"."seance" to "authenticated";

grant truncate on table "public"."seance" to "authenticated";

grant update on table "public"."seance" to "authenticated";

grant delete on table "public"."seance" to "service_role";

grant insert on table "public"."seance" to "service_role";

grant references on table "public"."seance" to "service_role";

grant select on table "public"."seance" to "service_role";

grant trigger on table "public"."seance" to "service_role";

grant truncate on table "public"."seance" to "service_role";

grant update on table "public"."seance" to "service_role";

grant delete on table "public"."utilisateur" to "anon";

grant insert on table "public"."utilisateur" to "anon";

grant references on table "public"."utilisateur" to "anon";

grant select on table "public"."utilisateur" to "anon";

grant trigger on table "public"."utilisateur" to "anon";

grant truncate on table "public"."utilisateur" to "anon";

grant update on table "public"."utilisateur" to "anon";

grant delete on table "public"."utilisateur" to "authenticated";

grant insert on table "public"."utilisateur" to "authenticated";

grant references on table "public"."utilisateur" to "authenticated";

grant select on table "public"."utilisateur" to "authenticated";

grant trigger on table "public"."utilisateur" to "authenticated";

grant truncate on table "public"."utilisateur" to "authenticated";

grant update on table "public"."utilisateur" to "authenticated";

grant delete on table "public"."utilisateur" to "service_role";

grant insert on table "public"."utilisateur" to "service_role";

grant references on table "public"."utilisateur" to "service_role";

grant select on table "public"."utilisateur" to "service_role";

grant trigger on table "public"."utilisateur" to "service_role";

grant truncate on table "public"."utilisateur" to "service_role";

grant update on table "public"."utilisateur" to "service_role";


  create policy "Enable insert for authenticated users only"
  on "public"."info_articles"
  as permissive
  for insert
  to authenticated
with check (true);



  create policy "Lecture publique articles"
  on "public"."info_articles"
  as permissive
  for select
  to public
using (true);



  create policy "Modifier par les admins"
  on "public"."info_articles"
  as permissive
  for update
  to public
using (true);



  create policy "Modifier ressources"
  on "public"."info_articles"
  as permissive
  for update
  to authenticated
using (true);



  create policy "Suppression pour les admins"
  on "public"."info_articles"
  as permissive
  for delete
  to authenticated
using (true);



  create policy "Lecture publique ressources"
  on "public"."info_resources"
  as permissive
  for select
  to public
using (true);



  create policy "Enable read access for all users"
  on "public"."mode_respiratoire"
  as permissive
  for select
  to public
using (true);


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


